### ISSUE TITLE
Error at page: /configuregateways.php

### ISSUE THREAD

**Issue by imintifydev** [0100Dev/WHMCS-Mollie-Payments#98] opened 2023-01-27 19:10 UTC
Hallo ik krijg een error wanneer ik de gateway wil activeren:
Hello I get an error after upload the folder and try to activate 
Error at page: /configuregateways.php

Latest version whmcs
php 7.4
ionCube 12.05

=====
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

Whoops\Exception\ErrorException: require_once(): Failed opening required '//modules/gateways/mollie/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /modules/gateways/mollie/mollie.php:3
Stack trace:
#0 /vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/...', 3)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by imintifydev** [comment] 2023-02-07 20:32
Any idea?

**Comment by Wouter0100** [comment] 2023-02-15 10:37
Duplicate of #44

**Closed by Wouter0100** 2023-02-15 10:37 UTC
