### ISSUE TITLE
Error gateway page

### ISSUE THREAD

**Issue by Giany70** [0100Dev/WHMCS-Mollie-Payments#68] opened 2020-08-25 21:16 UTC
Hi, I put the module in the folders and if I go to the gateway page I get this: 
![image](https://user-images.githubusercontent.com/32979108/91228717-06ae8f00-e729-11ea-8960-16aeff4b27fb.png)

**Comment by devaqto** [comment] 2020-08-25 21:20
Tja, lezen is ook een kunst!

**Comment by Wouter0100** [comment] 2020-08-26 14:33
Duplicate of #44 en #67

**Closed by Wouter0100** 2020-08-26 14:33 UTC
