### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by soniXx123** [0100Dev/WHMCS-Mollie-Payments#63] opened 2020-05-07 07:42 UTC
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Whoops\Exception\ErrorException: require_once(): Failed opening required '/XXXXXXXX/clients/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /XXXXXXXX/clients/modules/gateways/mollie/mollie.php:3
Stack trace:
#0 /XXXXXXXX/clients/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/XXXXXXXX/...', 3)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

I have now all the time after upload on the payment gateway page. 
any idea?

**Comment by shahidmalla1337** [comment] 2020-05-08 02:07
because of the file which is not found in that folder that's called by code line 3

**Comment by Wouter0100** [comment] 2020-05-18 08:19
It's working perfeclty fine. You haven't downloaded the correct file and/or did not install composer.

**Comment by Wouter0100** [comment] 2020-08-17 18:23
Duplicate of #44

**Closed by Wouter0100** 2020-08-17 18:23 UTC
