### ISSUE TITLE
Issue with getting this to work

### ISSUE THREAD

**Issue by dutchcg** [0100Dev/WHMCS-Mollie-Payments#65] opened 2020-08-17 12:16 UTC
When i upload the src folder i get Oops in WHMCS.
When i check the log the file mollie.php is looking for : require_once __DIR__ . '/vendor/autoload.php';

This is not added here in the repository.

**Comment by Wouter0100** [comment] 2020-08-17 18:22
Duplicate of #63

**Closed by Wouter0100** 2020-08-17 18:22 UTC
