### ISSUE TITLE
No support WHMCS 8.1

### ISSUE THREAD

**Issue by EricExtremeHash** [0100Dev/WHMCS-Mollie-Payments#81] opened 2021-03-14 16:58 UTC
Installed this module on WHMCS 8.1, While trying to checkout it's giving the following error:

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

**Comment by lutjebroeker** [comment] 2021-03-25 08:12
Whoops\Exception\ErrorException: require_once(): Failed opening required '/root/html/mijn/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /root/html/mijn/modules/gateways/mollie/mollie.php:3
Stack trace:
#0 /root/html/mijn/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/root/html...', 3)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by lutjebroeker** [comment] 2021-03-25 08:13
> Installed this module on WHMCS 8.1, While trying to checkout it's giving the following error:
> 
> Oops!
> Something went wrong and we couldn't process your request.
> Please go back to the previous page and try again.

Yes updated my self also it is a vendor issue i think

**Comment by Wouter0100** [comment] 2021-03-25 13:51
@lutjebroeker your issue is a duplicate of #44.

@EricExtremeHash please enable error logging and try again.

**Closed** 2021-03-25 13:52 UTC

**Comment by EricExtremeHash** [comment] 2021-03-25 14:20
@Wouter0100 
Error: Undefined class constant 'MAJOR_VERSION' in /home/jellebz436/domains/hosting.pcbyte.be/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Utils.php:121
Stack trace:
#0 /home/jellebz436/domains/hosting.pcbyte.be/public_html/vendor/guzzlehttp/guzzle/src/functions.php(61): GuzzleHttp\Utils::defaultUserAgent()
#1 /home/jellebz436/domains/hosting.pcbyte.be/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(194): GuzzleHttp\default_user_agent()
#2 /home/jellebz436/domains/hosting.pcbyte.be/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client->configureDefaults(Array)
#3 /home/jellebz436/domains/hosting.pcbyte.be/public_html/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/MollieApiClient.php(269): GuzzleHttp\Client->__construct(Array)
#4 /home/jellebz436/domains/hosting.pcbyte.be/public_html/modules/gateways/mollie/mollie.php(47): Mollie\Api\MollieApiClient->__construct()
#5 /home/jellebz436/domains/hosting.pcbyte.be/public_html/modules/gateways/molliekbc_devapp.php(21): mollie_link(Array, 'kbc')
#6 /home/jellebz436/domains/hosting.pcbyte.be/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): molliekbc_devapp_link(Array)
#7 /home/jellebz436/domains/hosting.pcbyte.be/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call('link', Array)
#8 /home/jellebz436/domains/hosting.pcbyte.be/public_html/vendor/whmcs/whmcs-foundation/lib/Invoice.php(0): WHMCS\Module\Gateway->call('link', Array)
#9 /home/jellebz436/domains/hosting.pcbyte.be/public_html/vendor/whmcs/whmcs-foundation/lib/Mail/Entity/Invoice.php(0): WHMCS\Invoice->getPaymentLink()
#10 /home/jellebz436/domains/hosting.pcbyte.be/public_html/vendor/whmcs/whmcs-foundation/lib/Mail/Emailer.php(0): WHMCS\Mail\Entity\Invoice->getEntitySpecificMergeData(53, '')
#11 /home/jellebz436/domains/hosting.pcbyte.be/public_html/vendor/whmcs/whmcs-foundation/lib/Mail/Emailer.php(0): WHMCS\Mail\Emailer->prepare()
#12 /home/jellebz436/domains/hosting.pcbyte.be/public_html/includes/functions.php(0): WHMCS\Mail\Emailer->send()
#13 /home/jellebz436/domains/hosting.pcbyte.be/public_html/includes/orderfunctions.php(0): sendMessage('Invoice Created', 53)
#14 /home/jellebz436/domains/hosting.pcbyte.be/public_html/cart.php(0): calcCartTotals(Object(WHMCS\User\Client), true, false)
#15 {main}

**Comment by Wouter0100** [comment] 2021-03-25 14:24
@EricExtremeHash zie #71.
