### ISSUE TITLE
whmcs 8.0 - error in payment gateway - missing file - /vendor/autoload.php

### ISSUE THREAD

**Issue by webstu-code** [0100Dev/WHMCS-Mollie-Payments#70] opened 2020-09-29 04:11 UTC
Hey there just upgraded to whmcs 8 + installed latestest version of this module

Getting an error when clicking into payment gateways

Whoops\Exception\ErrorException: require_once(): Failed opening required '/home/****/public_html/clients/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/****/public_html/clients/modules/gateways/mollie/mollie.php:3
Stack trace:
#0 /home/****/public_html/clients/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home/****/...', 3)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

Looked at the file

mollie/mollie.php
seems to be calling a file that does not exist in the github pull 

mollie/vendor/autoload.php'

(there is no vendor folder there)

Is there meant to be one?

Thanks 

James

**Comment by theemstra** [comment] 2020-09-29 05:51
Hi,

It seems like you dont have the dependencies installed. Did you run composer install?

**Comment by Wouter0100** [comment] 2020-09-30 08:34
Duplicate of #44

**Closed by Wouter0100** 2020-09-30 08:34 UTC
